site_name: pfi
site_description: Documentation for the package PFI (Probability Flow Inference).
site_author: Victor Chard√®s & Suryanarayana Maddu
repo_url: https://github.com/vchz/pfi/
repo_name: pfi
theme:
  name: material
  features:
        - navigation.tabs
        - navigation.tabs.sticky
        - toc.integrate
        - content.action.edit
        - content.action.view
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs/
extra_css:
  - style/custom_style.css
exclude_docs: |
    tests/
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [./pfi]
          options:
            docstring_style: numpy
            docstring_section_style: list
            inherited_members: true
            show_root_heading: true
            show_signature: true
            show_source: true
            heading_level: 2
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            merge_init_into_class: true
            type_parameter_headings: true
            filters:
              - "^__init__$"
              - "!^__.*__$"
              - "!^_.*"
              - "!forward"
  - mkdocs-autoapi:
        autoapi_dir: pfi  
        autoapi_keep_files: true  
        autoapi_root: api
        autoapi_add_nav_entry: false
nav:
  - Getting started: index.md
  - Documentation: api/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences